sudo: required
services:
  - docker

before_install:
  - docker build -t MoeTammam/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true MoeTammam/docker-react npm run test -- --coverage